services:
  app:
    build: .
    ports:
      - "4000:3000"
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
