name: Ejecutar tests de Node.js

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [16, 18, 20]

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar ESlint
        run: npx eslint . --fix

      - name: Revisar formato con Prettier
        run: npx prettier --check


      - name: Ejecutar pruebas
        run: npm test
